WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using WowCarry.Domain.Entities;
using WowCarry.Domain.Abstract;
using WebUI.Models;
using System;

namespace WowCarry.WebUI.Controllers
{
    public  class CartController : Controller
    {

        IEntityRepository EntityRepository;
        public CartController(IEntityRepository EntityRep)
        {
            EntityRepository = EntityRep;
        }
        public PartialViewResult CartPopUp(Cart cart)
        {
            return PartialView(cart);
        }
        [HttpPost]
        public ActionResult RemoveFromCart(Cart cart,Guid productId)
        {
            Product product = EntityRepository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return PartialView("CartPopUp", cart);
        }
        public PartialViewResult UpdateCart(Cart cart)
        {
            return PartialView("CartPopUp", cart);
        }
    }
}

WebUI/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WowCarry.Domain.Abstract;
using WowCarry.Domain.Entities;

namespace WebUI.Controllers
{
    public class HomePageController : Controller
    {
        IEntityRepository EntityRepository;
        public HomePageController(IEntityRepository entityRepo)
        {
            EntityRepository = entityRepo;
        }
        public ActionResult Home()
        {
            Session["SelectedGame"] = "Select Game";
            return View();
        }
        public PartialViewResult RecommendedProducts(string game)
        {
            IEnumerable<Product> result = EntityRepository.Products.Where(p=>p.ProductGame.GameName == game).Take(4);
            return PartialView(result);
        }
        public ViewResult AboutUs()
        {
            return View();

        }
        public ViewResult Contacts()
        {
            return View();
        }
        public ViewResult FAQ()
        {
            return View();
        }
        public ViewResult PrivacyPolicy()
        {
            return View();
        }
        public ViewResult Terms()
        {
            return View();
        }
        public ViewResult CarryCoins()
        {
            return View();
        }

        [HttpPost]
        public void SetSessionData(Dictionary<string,string> dict)
        {
            if (dict.Count() > 0)
            {
                foreach (var keyValuePair in dict)
                {
                    Session[keyValuePair.Key] = keyValuePair.Value;
                }
            }
        }
    }
}

WebUI/Controllers/NavigationController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

using WebUI.Models;
using WowCarry.Domain.Abstract;
using WowCarry.Domain.Entities;

namespace WebUI.Controllers
{
    public class NavigationController : Controller
    {
        IEntityRepository EntityRepository;

        public NavigationController(IEntityRepository entityRepo)
        {
            EntityRepository = entityRepo;
        }
        public PartialViewResult GameMenu()
        {
            IEnumerable<ProductGame> games = EntityRepository.Products.Select(p => p.ProductGame).Distinct();
            return PartialView(games);
        }
        public PartialViewResult CategoryMenu(string currentGame)
        {
            GetCurrentGame(currentGame);
            string selectedUrl = EntityRepository.Products.Where(p => p.ProductGame.GameName == (string)Session["SelectedGame"]).Select(p => p.ProductGame.GameShortUrl).FirstOrDefault();

            CategoryViewModel result = new CategoryViewModel
            {
                categories = EntityRepository.Products.Where(p => p.ProductGame.GameName == (string)Session["SelectedGame"]).Select(p => p.ProductCategory.ProductCategoryName).Distinct().OrderBy(x => x),
                currentGame = selectedUrl
            };
            return PartialView(result);
        }
        public PartialViewResult GameCategoryMenu(bool isMobile = false)
        {
            var cat = EntityRepository.Products.Select(p => p.ProductCategory).Select(c => new { c.ProductGame.GameName, c.ProductCategoryName }).Distinct();

            GameCategoryViewModel model = new GameCategoryViewModel
            {
                Games = EntityRepository.Products.Select(p => p.ProductGame).Distinct(),
                ProductCategories = cat.AsEnumerable().Select(item => new KeyValuePair<string, string>(item.GameName, item.ProductCategoryName)).ToList()
            };

            if (isMobile)
                return PartialView("MobileMenu", model);

            return PartialView(model);
        }
        public void GetCurrentGame(string currentGame)
        {
            Session["SelectedGame"] = string.IsNullOrEmpty(currentGame)? (string)Session["SelectedGame"] : EntityRepository.Products.Where(p => p.ProductGame.GameShortUrl == currentGame).Select(p => p.ProductGame.GameName).FirstOrDefault();
        }
    }
}

WebUI/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WebUI.Models;

using WowCarry.Domain.Abstract;
using WowCarry.Domain.Entities;

namespace WowCarry.WebUI.Controllers
{
    public class ProductDetailsController : Controller
    {
        IEntityRepository EntityRepository;
        public ProductDetailsController(IEntityRepository entityRepo)
        {
            EntityRepository = entityRepo;
        }
        public ViewResult Details(string productUrl)
        {
            Product product = EntityRepository.Products.Where(p => p.SEO.UrlKeyWord == productUrl).FirstOrDefault();
            return View(product);
        }
        [HttpPost]
        public decimal AddToCart (Cart cart ,Guid? ProductId)
        {
            Product product = EntityRepository.Products.Where(p => p.ProductId == ProductId).FirstOrDefault();
            cart.AddItem(product);

            return cart.TotalQty();
        }
    }
    
}

WebUI/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

using WebUI.Controllers;
using WebUI.Models;

using WowCarry.Domain.Abstract;
using WowCarry.Domain.Entities;

namespace WowCarry.WebUI.Controllers
{
    public class ProductsController : Controller
    {
        IEntityRepository EntityRepository;
        public int pageSize = 3;
        public ProductsController(IEntityRepository entityRepo)
        {
            EntityRepository = entityRepo;
        }
        public ViewResult List(string selectedGame, string categoryName,int page = 1)
        {
            if (!string.IsNullOrEmpty(selectedGame))
            {
                Session["SelectedGame"] = EntityRepository.Products.Where(p => p.ProductGame.GameShortUrl == selectedGame).Select(p => p.ProductGame.GameName).FirstOrDefault();
            }

            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = EntityRepository.Products.Where(p => categoryName == null || p.ProductCategory.ProductCategoryName == categoryName && p.ProductGame.GameShortUrl == selectedGame)
                .OrderBy(p => p.ProductUpdateDate)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = categoryName == null ? EntityRepository.Products.Count() : EntityRepository.Products.Where(p => p.ProductCategory.ProductCategoryName == categoryName && p.ProductGame.GameShortUrl == (string)Session["SelectedGame"]).Count()
                },
                CurrentCategory = categoryName,
                productCategory = EntityRepository.Products.Where(p => categoryName == null || p.ProductCategory.ProductCategoryName == categoryName).Select(p => p.ProductCategory).FirstOrDefault()
            };
            return View(model);
        }
    }
}

WebUI/Views/Shared/ProductsView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/CSS/Styles.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>

<body>
    <div class="cover">
        <header>
            <div class="top">
                <div id="content">
                    <a class="navbar-brand" href="#">WowCarry</a>
                </div>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <div id="categories" class="col-xs-3">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    </nav>
                </div>
                <div id="content" class="col-sm-12">
                    <div class="clear"></div>

                </div>
            </div>
        </div>
        <div class="clear-footer"></div>
    </div>

    <footer>
        <div id="content">
            footer
        </div>
    </footer>
</body>
</html>
<!-- Классы navbar и navbar-default (базовые классы меню) -->
<nav class="navbar navbar-default">
    <!-- Контейнер (определяет ширину Navbar) -->
    <div class="container-fluid">
        <!-- Заголовок -->
        <div class="navbar-header">
            <!-- Кнопка «Гамбургер» отображается только в мобильном виде (предназначена для открытия основного содержимого Navbar) -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Бренд или название сайта (отображается в левой части меню) -->
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <!-- Основная часть меню (может содержать ссылки, формы и другие элементы) -->
        <div class="collapse navbar-collapse" id="navbar-main">
            <!-- Содержимое основной части -->
        </div>
    </div>
</nav>

WebUI/Views/Shared/SiteBlockChild.cshtml
@model WowCarry.Domain.Entities.HtmlBlocksChildren

<div class="@Model.CSSClass">
    @if (!String.IsNullOrEmpty(Model.Image))
    {
        <div class="image"><img alt=@Model.Title src=@Model.Image /></div>
    }
    @if (!String.IsNullOrEmpty(Model.Title))
    {
        <div class="title">@Model.Title</div>
    }
    @if (!String.IsNullOrEmpty(Model.Text))
    {
<div class="text">@Html.Raw(HttpUtility.HtmlDecode(@Model.Text)) </div>
    }
</div>

WebUI/Views/Shared/_Footer.cshtml
<div class="clear-footer"></div>
    </div>

<footer>

    <div class="container">
        <div class="row">
            <div class="logo_foot">
                <a href="/"><img src="~/Images/logo.svg" alt="logo" /></a>
            </div>

            <div class="clear"></div>
            <span class="main_blocks">
                <div class="col-sm-3 foot_menu">
                    <div class="title">Information</div>
                    <ul class="list-unstyled">
                        <li> @Html.ActionLink("ABOUT US", "AboutUs", "HomePage")</li>
                        <li> @Html.ActionLink("CONTACTS", "Contacts", "HomePage")</li>
                        <li> @Html.ActionLink("F.A.Q", "FAQ", "HomePage")</li>
                        <li>  @Html.ActionLink("PRIVACY POLICY", "PrivacyPolicy", "HomePage")</li>
                        <li>  @Html.ActionLink("TERMS & CONDITIONS", "Terms", "HomePage")</li>
                        <li>  @Html.ActionLink("CARRYCOINS", "CarryCoins", "HomePage")</li>
                    </ul>
                </div>

                <div class="col-sm-3 footer_category">
                    <div class="title">Games</div>
                    <ul class="list-unstyled">
                        @Html.Action("GameMenu", "Navigation")
                    </ul>
                </div>
                <div class="social_footer">
                    <div class="title">Social links</div>
                    <a href="skype:live:wowcarryshop?chat"><img src="/Images/mainImages/skype.svg" alt="skype" class="img-responsive"><span>&#64;wowcarryshop</span> </a>
                    <div class="disc_link">
                        <img src="/Images/mainImages/discord.svg" alt="discord" class="img-responsive"> <span>WowCarry#0001</span>
                        <div class="text_block" style="opacity: 0; z-index: -9;">
                            <p style="text-align: center;font-size:20px;">Code copied!</p>
                            <p style="text-align: center;font-size:20px;">Add us to your friends list :)</p>
                            <p style="text-align: center;"><br></p><p style="text-align: center;">Contact us fast via discord any time. We are available 24/7</p>
                            <div class="hidden_input"><input type="text" value="WowCarry#0001"></div>
                        </div>
                    </div>
                    <a href="https://twitter.com/wow_carry" target=" _blank"><img src="/Images/mainImages/twitter.svg" alt="twitter" class="img-responsive"><span>&#64;wow_carry</span></a>
                    <a href="https://www.facebook.com/wowcarry" target=" _blank"><img src="/Images/mainImages/facebook.svg" alt="facebook" class="img-responsive"><span>&#64;wowcarry</span></a>
                    <a href="https://www.instagram.com/wow_carry" target=" _blank"><img src="/Images/mainImages/instagram.svg" alt="instagram" class="img-responsive"><span>&#64;wow_carry</span> </a>
                    <a href="https://t.me/wowcarry" target=" _blank"><img src="/Images/mainImages/telegram_foot.svg" alt="instagram" class="img-responsive"><span>&#64;wowcarry</span> </a>
                </div>
                
            </span>
            <div class="clear"></div>
            <div class="pow">
                <p>WowCarry.com - Ingame boosting services 2020 ©</p>
                <p>All trademarks referenced herein are the properties of their respective owners.</p>
            </div>
            <div class="payment_accept">
                <div class="title">Payments we accept:</div>
                <span><img src="/Images/mainImages/PayPal_2014_logo.svg" alt="paypal" class="img-responsive"></span>
                <span><img src="/Images/mainImages/Discover-02.svg" alt="discover" class="img-responsive"></span>
                <span><img src="/Images/mainImages/Visa_2014_logo_detail 1.svg" alt="visa" class="img-responsive"></span>
                <span><img src="/Images/mainImages/Mastercard-logo.svg" alt="mastercard" class="img-responsive"></span>
            </div>
        </div>
    </div>
</footer>
<script src="~/Scripts/accardeon.js"></script>
<script>
    //discord copy link
    function hideText() {
        $(".social_footer .disc_link .text_block").css({ "opacity": "0", "z-index": "-9" });
    }
    $(".social_footer .disc_link").on("click", function () {
        var copyText = $(".hidden_input input");
        copyText.select();
        document.execCommand("copy");
        $(".social_footer .disc_link .text_block").css({ "opacity": "1", "z-index": "1" });
        setTimeout(hideText, 5000);
    });
    $(document).mouseup(function (e) {
        var container = $(".social_footer .disc_link .text_block");
        if (container.has(e.target).length === 0) {
            container.css({ "opacity": "0", "z-index": "-9" });
        }
    });

    //footer menu
    $(".foot_menu .title").on("click", function () {
        if ($(".foot_menu").hasClass("active_menu")) {
            $(".foot_menu").removeClass("active_menu");
        } else {
            $(".foot_menu").addClass("active_menu");
        }
    });
    $(".footer_category .title").on("click", function () {
        if ($(".footer_category").hasClass("active_menu")) {
            $(".footer_category").removeClass("active_menu");
        } else {
            $(".footer_category").addClass("active_menu");
        }
    });
</script>

</script>
</body>
</html>

WebUI/Views/Shared/_Header.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/Slick/slick.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link rel="icon" href="/Images/icon-site.png" type="image/x-icon">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/bootstrap-select.min.css">
    <script src="~/Scripts/bootstrap-select.min.js"></script>

    <link href="~/Content/CSS/Styles.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

</head>

<body>
    <div class="@(Request.Browser.IsMobileDevice ? "cover mobile-cover" : "cover")">
        <header>
            <div class="top">
                <div id="content">
                    @if (Request.Browser.IsMobileDevice)
                    {
                        @Html.Action("GameCategoryMenu", "Navigation", new { isMobile = true })
                        <div id="logo-mobile"><a href="/"> <img src="~/Images/logo.svg" alt="logo" /> </a></div>
                    }
                    else
                    {
                        <div id="logo"><a href="/"> <img src="~/Images/logo.svg" alt="logo" /> </a></div>
                        <div class="games-top-menu-block">
                            <div class="hover-button">
                                
                                
                                    <div class="no-category" style="display: inline-block;">@Session["SelectedGame"]</div>
                                

                                <i class="fa"></i>
                            </div>
                            <ul class="dropdown-menu">
                                @Html.Action("GameMenu", "Navigation")
                            </ul>
                        </div>
                        <div class="top_curr">
                            <div class="top_currency">
                                <div class="pull-left">
                                    <form action="" method="post" enctype="multipart/form-data" id="form-currency">
                                        <div class="btn-group">
                                            <div class="hover-button">
                                                <span> Europe </span>
                                                <i class="fa"></i>
                                            </div>
                                            <ul class="dropdown-menu">
                                                <li>
                                                    <button class="currency-select btn btn-link btn-block" type="button" name="EUR">Europe</button>
                                                </li>
                                                <li>
                                                    <button class="currency-select btn btn-link btn-block" type="button" name="USD">US&amp;Oceania</button>
                                                </li>
                                            </ul>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                    <button id="toggleCart" type="button" class="btn-cart" data-toggle="modal" data-target="#cartModal">
                        Cart<span>(<span id="qty"></span>)</span>
                    </button>
                    <div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
                        @Html.Action("CartPopUp", "Cart")
                    </div>

                    <div class="account_block">
                        <ul class="list-inline">
                            <li>
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <span class="txt_acc">My Account</span>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" data-toggle="modal" data-target="#registerModal">Register</a></li>
                                        <li><a href="#" data-toggle="modal" data-target="#loginModal">Login</a></li>
                                    </ul>
                                }
                                else
                                {
                                    <span class="txt_acc">@User.Identity.Name</span>
                                    <ul class="dropdown-menu">
                                        <li> <div class="login-user"> @Html.ActionLink("Logout", "CustomerLogout", "Login")</div></li>
                                    </ul>
                                }
                            </li>
                        </ul>
                    </div>
                    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
                        @Html.Action("Login", "Login", new { isWebView = true })
                    </div>
                    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
                        @Html.Action("Registration", "Login")
                    </div>

                    <form action="" class="search-bar">

                        <button class="btn btn-primary search-btn" type="submit">
                            Search
                        </button>
                    </form>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="bottom">
                <div id="content">
                    <div class="navbar" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            @if(!Request.Browser.IsMobileDevice)
                            {
                                @Html.Action("CategoryMenu", "Navigation")
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <script>
            $(document).on("click", ".remove_block button", function () {
                var prodId = $(this).closest('.cart-block').find('input').val();
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@Url.Action("RemoveFromCart", "Cart")",
                    data: {
                        productId: prodId
                    },
                    success: function (data) {
                        $("#cartModal").html(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        console.log(thrownError)
                    }
                });
            });

            $("#toggleCart").click(function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "@Url.Action("UpdateCart", "Cart")",
                    success: function (data) {
                        $("#cartModal").html(data);
                    }
                });
            });

            var data = new Object();
            data['TimeZone'] = Intl.DateTimeFormat().resolvedOptions().timeZone;
            data['Region'] = 'US';

            $.ajax({
                cache: false,
                type: "POST",
                url: "@Url.Action("SetSessionData", "HomePage")",
                data: {
                    dict: data
                }
            });
        </script>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/CSS/Styles.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>

<body>
    <div class="cover">
        <header>
            <div class="top">
                <div id="content">
                    <a class="navbar-brand" href="#">WowCarry</a>
                </div>
            </div>
        </header>

        <div class="container-fluid">
            <div class="row">
                <div id="categories" class="col-xs-3">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto">
                                @Html.Action("Menu", "Nav")
                            </ul>
                        </div>
                    </nav>
                </div>
                <div id="content" class="col-sm-12">

                    @RenderBody()
                    <div class="clear"></div>

                </div>
            </div>
        </div>
        <div class="clear-footer"></div>
    </div>

    <footer>
        <div id="content">
            footer
        </div>
    </footer>
</body>
</html>
<!-- Классы navbar и navbar-default (базовые классы меню) -->
<nav class="navbar navbar-default">
    <!-- Контейнер (определяет ширину Navbar) -->
    <div class="container-fluid">
        <!-- Заголовок -->
        <div class="navbar-header">
            <!-- Кнопка «Гамбургер» отображается только в мобильном виде (предназначена для открытия основного содержимого Navbar) -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- Бренд или название сайта (отображается в левой части меню) -->
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <!-- Основная часть меню (может содержать ссылки, формы и другие элементы) -->
        <div class="collapse navbar-collapse" id="navbar-main">
            <!-- Содержимое основной части -->
        </div>
    </div>
</nav>

WebUI/Views/Shared/_ProductDetails.cshtml
<div id="product-detales" class="container">
    <div class="row">
        <div id="content">
            
            <div class="main-blocks">PRODUCT DETAILS</div>
        </div>
    </div>
</div>

WebUI/Views/Shared/_ProductDetales.cshtml
@RenderPage("~/Views/Shared/_Header.cshtml")

<div id="product-detales" class="container">
    <div class="row">
        <div id="content">
            
            <div class="main-blocks">PRODUCT DETALES</div>
        </div>
    </div>
</div>

@RenderPage("~/Views/Shared/_Footer.cshtml")